# Generated by Django 4.2.6 on 2023-12-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="host",
            field=models.CharField(default="0.0.0.0", max_length=50),
        ),
    ]
